version: '3.8'

services:
  # Service backend (FastAPI)
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: calculator-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      #interval: 30s
      #timeout: 10s
      #retries: 3
      #start_period: 5s
    networks:
      - calculator-network

  # Service frontend (interface utilisateur)
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: calculator-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge
