version: '3.8'

services:
  # Service backend (FastAPI)
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: calculator-api
    ports:
      - "30800:8000"   # Accessible sur http://172.20.10.3:30800
    restart: unless-stopped
    networks:
      - calculator-network

  # Service frontend (interface utilisateur avec HTTPS)
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: calculator-frontend
    ports:
      - "30080:443"    # Accessible sur https://172.20.10.3:30080
      - "30081:80"     # Redirection HTTP (optionnel)
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge